### ISSUE TITLE
Trained Connect 4 model?

### ISSUE THREAD

**Issue by Bobingstern** [bhansconnect/fast-alphazero-general#3]
Is there any chance you have the trained model for connect 4 lying around? I could train it again on my RTX 2060 but it would be easier if you could add it to the repo similar to the original alphazero-general. The reason I ask is that I would like to run some tests on it against myself and a minimax agent. Also, is there any way I could couple 2 machines and utilize both of their GPUs to train the agent even faster? Thanks

**Comment by bhansconnect** [comment]
I don't, sorry. I haven't touched this code in a very long time. If you want a model fast, I advise using [bhansconnect/alphazero-pybind11](https://github.com/bhansconnect/alphazero-pybind11) instead. It runs many times faster due to moving parts of the computation into c++.

Neither of these repros support multidevice training. That being said, if you only want to support a few devices, it is possible to setup a network drive where the training data and networks would be stored. You would need to modify the code to allow a second executable to essential just play games. It would play games until hitting the goal number of games for the iteration, wait for the new network to be trained on the main device, and repeat. That would only require minimal file based coordination.

**Comment by HoblikDotJs** [comment]
I have a few. Do you want the full history? Its 10GB and 413 iterations. 
I can send you just the [last one](https://drive.google.com/file/d/17mRy8bb03SV1dDuKUk5N3_PEA9HenUGT/view?usp=sharing) tho.

**Comment by Bobingstern** [comment]
> I have a few. Do you want the full history? Its 10GB and 413 iterations. 
> 
> I can send you just the [last one](https://drive.google.com/file/d/17mRy8bb03SV1dDuKUk5N3_PEA9HenUGT/view?usp=sharing) tho. 

Thanks! I'll only need the last one though.

**Comment by Bobingstern** [comment]
> I don't, sorry. I haven't touched this code in a very long time. If you want a model fast, I advise using [bhansconnect/alphazero-pybind11](https://github.com/bhansconnect/alphazero-pybind11) instead. It runs many times faster due to moving parts of the computation into c++.
> 
> 
> 
> Neither of these repros support multidevice training. That being said, if you only want to support a few devices, it is possible to setup a network drive where the training data and networks would be stored. You would need to modify the code to allow a second executable to essential just play games. It would play games until hitting the goal number of games for the iteration, wait for the new network to be trained on the main device, and repeat. That would only require minimal file based coordination.

I would use the new repo but my experience with c++ ends with basic memory management and compiling with mingw. I haven't a clue on how to run the code or anything.

**Comment by bhansconnect** [comment]
> I would use the new repo but my experience with c++ ends with basic memory management and compiling with mingw. I haven't a clue on how to run the code or anything.

That's totally valid. I didn't do a particularly great job at documenting that either. I might eventually revisit making that more beginner friendly, but the speed gains from simulating games in c++ is huge. Definitely worth it if you want more performance. I mostly made it so that I could tackle larger/more interesting games on a single machine.

**Comment by Bobingstern** [comment]
> > I would use the new repo but my experience with c++ ends with basic memory management and compiling with mingw. I haven't a clue on how to run the code or anything.
> 
> 
> 
> That's totally valid. I didn't do a particularly great job at documenting that either. I might eventually revisit making that more beginner friendly, but the speed gains from simulating games in c++ is huge. Definitely worth it if you want more performance. I mostly made it so that I could tackle larger/more interesting games on a single machine.

Would you mind giving me a few pointers on how to run it? I would really like to get that going with more complex games. I think I know what meson is but not what ninja is or what python file to run to start training. I think it's the game_runner file but I'm not sure

**Comment by bhansconnect** [comment]
I have never run it on windows, let me give that a try and document it more clearly.

**Comment by bhansconnect** [comment]
I just got it running on windows (though the nice training visualization and tracking library doesn't support windows) and greatly expanded the readme. Maybe that will make usable for others. Don't feel any pressure to use it, but it is available.

[bhansconnect/alphazero-pybind11](https://github.com/bhansconnect/alphazero-pybind11)

**Comment by Bobingstern** [comment]
This is great! I'll close the issue now, thanks for the help
